// Test-only stand-in for GLEW on Linux: the FFGL SDK calls GL through
// GLEW's function pointers, which this fills from the current EGL context.
extern "C" void* eglGetProcAddress(const char*);
extern "C" { void* __glewActiveTexture = nullptr; }
extern "C" { void* __glewAttachShader = nullptr; }
extern "C" { void* __glewBindBuffer = nullptr; }
extern "C" { void* __glewBindFramebuffer = nullptr; }
extern "C" { void* __glewBindRenderbuffer = nullptr; }
extern "C" { void* __glewBindVertexArray = nullptr; }
extern "C" { void* __glewBufferData = nullptr; }
extern "C" { void* __glewCheckFramebufferStatus = nullptr; }
extern "C" { void* __glewCompileShader = nullptr; }
extern "C" { void* __glewCreateProgram = nullptr; }
extern "C" { void* __glewCreateShader = nullptr; }
extern "C" { void* __glewDeleteBuffers = nullptr; }
extern "C" { void* __glewDeleteFramebuffers = nullptr; }
extern "C" { void* __glewDeleteProgram = nullptr; }
extern "C" { void* __glewDeleteRenderbuffers = nullptr; }
extern "C" { void* __glewDeleteShader = nullptr; }
extern "C" { void* __glewDeleteVertexArrays = nullptr; }
extern "C" { void* __glewEnableVertexAttribArray = nullptr; }
extern "C" { void* __glewFramebufferRenderbuffer = nullptr; }
extern "C" { void* __glewFramebufferTexture2D = nullptr; }
extern "C" { void* __glewGenBuffers = nullptr; }
extern "C" { void* __glewGenFramebuffers = nullptr; }
extern "C" { void* __glewGenRenderbuffers = nullptr; }
extern "C" { void* __glewGenVertexArrays = nullptr; }
extern "C" { void* __glewGetProgramInfoLog = nullptr; }
extern "C" { void* __glewGetProgramiv = nullptr; }
extern "C" { void* __glewGetShaderInfoLog = nullptr; }
extern "C" { void* __glewGetShaderiv = nullptr; }
extern "C" { void* __glewGetUniformLocation = nullptr; }
extern "C" { void* __glewLinkProgram = nullptr; }
extern "C" { void* __glewRenderbufferStorage = nullptr; }
extern "C" { void* __glewShaderSource = nullptr; }
extern "C" { void* __glewTransformFeedbackVaryings = nullptr; }
extern "C" { void* __glewUniform1f = nullptr; }
extern "C" { void* __glewUniform1i = nullptr; }
extern "C" { void* __glewUniform2f = nullptr; }
extern "C" { void* __glewUniform3f = nullptr; }
extern "C" { void* __glewUniform4f = nullptr; }
extern "C" { void* __glewUseProgram = nullptr; }
extern "C" { void* __glewVertexAttribPointer = nullptr; }
void glewShimInit() {
  __glewActiveTexture = eglGetProcAddress("glActiveTexture");
  __glewAttachShader = eglGetProcAddress("glAttachShader");
  __glewBindBuffer = eglGetProcAddress("glBindBuffer");
  __glewBindFramebuffer = eglGetProcAddress("glBindFramebuffer");
  __glewBindRenderbuffer = eglGetProcAddress("glBindRenderbuffer");
  __glewBindVertexArray = eglGetProcAddress("glBindVertexArray");
  __glewBufferData = eglGetProcAddress("glBufferData");
  __glewCheckFramebufferStatus = eglGetProcAddress("glCheckFramebufferStatus");
  __glewCompileShader = eglGetProcAddress("glCompileShader");
  __glewCreateProgram = eglGetProcAddress("glCreateProgram");
  __glewCreateShader = eglGetProcAddress("glCreateShader");
  __glewDeleteBuffers = eglGetProcAddress("glDeleteBuffers");
  __glewDeleteFramebuffers = eglGetProcAddress("glDeleteFramebuffers");
  __glewDeleteProgram = eglGetProcAddress("glDeleteProgram");
  __glewDeleteRenderbuffers = eglGetProcAddress("glDeleteRenderbuffers");
  __glewDeleteShader = eglGetProcAddress("glDeleteShader");
  __glewDeleteVertexArrays = eglGetProcAddress("glDeleteVertexArrays");
  __glewEnableVertexAttribArray = eglGetProcAddress("glEnableVertexAttribArray");
  __glewFramebufferRenderbuffer = eglGetProcAddress("glFramebufferRenderbuffer");
  __glewFramebufferTexture2D = eglGetProcAddress("glFramebufferTexture2D");
  __glewGenBuffers = eglGetProcAddress("glGenBuffers");
  __glewGenFramebuffers = eglGetProcAddress("glGenFramebuffers");
  __glewGenRenderbuffers = eglGetProcAddress("glGenRenderbuffers");
  __glewGenVertexArrays = eglGetProcAddress("glGenVertexArrays");
  __glewGetProgramInfoLog = eglGetProcAddress("glGetProgramInfoLog");
  __glewGetProgramiv = eglGetProcAddress("glGetProgramiv");
  __glewGetShaderInfoLog = eglGetProcAddress("glGetShaderInfoLog");
  __glewGetShaderiv = eglGetProcAddress("glGetShaderiv");
  __glewGetUniformLocation = eglGetProcAddress("glGetUniformLocation");
  __glewLinkProgram = eglGetProcAddress("glLinkProgram");
  __glewRenderbufferStorage = eglGetProcAddress("glRenderbufferStorage");
  __glewShaderSource = eglGetProcAddress("glShaderSource");
  __glewTransformFeedbackVaryings = eglGetProcAddress("glTransformFeedbackVaryings");
  __glewUniform1f = eglGetProcAddress("glUniform1f");
  __glewUniform1i = eglGetProcAddress("glUniform1i");
  __glewUniform2f = eglGetProcAddress("glUniform2f");
  __glewUniform3f = eglGetProcAddress("glUniform3f");
  __glewUniform4f = eglGetProcAddress("glUniform4f");
  __glewUseProgram = eglGetProcAddress("glUseProgram");
  __glewVertexAttribPointer = eglGetProcAddress("glVertexAttribPointer");
}
