# Rasterizes the caption decoder's font ROM the way videoskillet's
# captionrom.ts does in the browser: each printable ASCII glyph drawn centred
# in an 8x12 cell at 11px DejaVu Sans Mono, a dot wherever coverage >= 96/255.
# DejaVu fonts: Bitstream Vera / DejaVu license, redistributable.
import sys
from PIL import Image, ImageDraw, ImageFont
W, H, FIRST, COUNT, INK = 8, 12, 0x20, 96, 96
font = ImageFont.truetype('/usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf', 11)
rows = []
for i in range(COUNT):
    ch = chr(FIRST + i)
    img = Image.new('L', (W, H), 0)
    d = ImageDraw.Draw(img)
    # canvas textAlign=center, textBaseline=middle at (W/2, H/2)
    d.text((W / 2, H / 2), ch, fill=255, font=font, anchor='mm')
    px = img.load()
    for y in range(H):
        bits = 0
        for x in range(W):
            if px[x, y] >= INK:
                bits |= 1 << x
        rows.append(bits)
out = sys.argv[1] if len(sys.argv) > 1 else '../engine/generated/captionrom.gen.h'
with open(out, 'w') as f:
    f.write('// GENERATED by tools/gen_caption_rom.py: 8x12 caption font ROM rasterized\n')
    f.write('// from DejaVu Sans Mono (Bitstream Vera / DejaVu font license).\n#pragma once\n#include <cstdint>\n')
    f.write('namespace skillet {\nconstexpr int GLYPH_W = 8, GLYPH_H = 12, GLYPH_FIRST = 0x20, GLYPH_COUNT = 96;\n')
    f.write('inline const uint32_t kCaptionFont[GLYPH_COUNT * GLYPH_H] = {\n')
    for g in range(COUNT):
        f.write('  ' + ', '.join('0x%02x' % b for b in rows[g * H:(g + 1) * H]) + ',  // %r\n' % chr(FIRST + g))
    f.write('};\n}\n')
# preview a few glyphs
for ch in 'SK':
    g = ord(ch) - FIRST
    print('\n'.join(''.join('#' if (rows[g * H + y] >> x) & 1 else '.' for x in range(W)) for y in range(H)))
    print()
