// Generates the C++ tables the engine needs straight from the videoskillet
// TypeScript sources, so the port reads the same control schema, uniform
// layout and preset catalog the app does instead of a hand-copied one.
//
//   node --experimental-transform-types --import ./register.mjs gen_tables.mjs <out.h>
import { writeFileSync } from 'node:fs'

const VS = process.env.VS ?? '/home/claude/videoskillet'
const out = process.argv[2] ?? '../engine/generated/tables.gen.h'

const { DEFAULT_CONTROLS, CONTROL_KEYS, STOCK_HOLD } = await import(`${VS}/src/core/controls.ts`)
const { PARAM_DEFS, PARAM_BYTES, TILE_WG } = await import(`${VS}/src/core/gpu/prelude.ts`)
const { PRESETS, ENUM_KEYS, needsSourceB } = await import(`${VS}/src/ui/presets.ts`)
const UI = await import(`${VS}/src/ui/controls.ts`)
const { toTravel, fromTravel } = await import(`${VS}/src/ui/travel.ts`)
const { CLIP_POINTS } = await import(`${VS}/src/core/signal/clip.ts`)

const num = v => {
  if (!Number.isFinite(v)) throw new Error(`non-finite ${v}`)
  const s = String(v)
  return /[.eE]/.test(s) ? s : `${s}.0`
}
const cstr = s => JSON.stringify(s).replace(/\\u([0-9a-f]{4})/gi, (_, h) => `\\u${h}`)
const keyIdx = new Map(CONTROL_KEYS.map((k, i) => [k, i]))

const L = []
L.push('// GENERATED by tools/gen_tables.mjs from the videoskillet sources. Do not edit.')
L.push('// videoskillet (c) 2026 Colin Diesh, MIT License.')
L.push('#pragma once')
L.push('#include <cstdint>')
L.push('namespace skillet {')
L.push('')

// ── controls ──
L.push(`constexpr int kNumControls = ${CONTROL_KEYS.length};`)
L.push('enum Ctl : int {')
CONTROL_KEYS.forEach((k, i) => L.push(`  C_${k} = ${i},`))
L.push('};')
L.push('inline const char* const kControlNames[kNumControls] = {')
L.push(CONTROL_KEYS.map(k => `  ${cstr(k)},`).join('\n'))
L.push('};')
L.push('inline const double kControlDefaults[kNumControls] = {')
L.push(CONTROL_KEYS.map(k => `  ${num(DEFAULT_CONTROLS[k])}, // ${k}`).join('\n'))
L.push('};')

// slider spans: min, max, step, choice count, travel curve id
const curveIds = { magnifier: 1, persistence: 2, shuttle: 3, synth: 4, zero: 5, unity: 6 }
L.push('struct SliderSpan { double min, max, step; int choices; int curve; const char* label; };')
L.push('inline const SliderSpan kSliders[kNumControls] = {')
for (const k of CONTROL_KEYS) {
  const s = UI.SLIDER_BY_KEY.get(k)
  if (!s) { L.push(`  { ${num(DEFAULT_CONTROLS[k])}, ${num(DEFAULT_CONTROLS[k])}, 1.0, 0, 0, ${cstr(k)} }, // ${k} (no slider)`); continue }
  L.push(`  { ${num(s.min)}, ${num(s.max)}, ${num(s.step)}, ${s.choices ? s.choices.length : 0}, ${s.curve ? curveIds[s.curve] : 0}, ${cstr(s.label)} }, // ${k}`)
}
L.push('};')

// key sets used by the glide and the stab gate
const keyList = (name, set) => {
  const ks = [...set].filter(k => keyIdx.has(k))
  L.push(`inline const int ${name}[] = { ${ks.map(k => `C_${k}`).join(', ')} };`)
  L.push(`constexpr int ${name}Count = ${ks.length};`)
}
keyList('kEnumKeys', ENUM_KEYS)
keyList('kViewKeys', UI.VIEW_KEYS)
keyList('kStockHold', STOCK_HOLD)
keyList('kFilterKeys', new Set(['encChromaMHz', 'demodMHz', 'chromaTail', 'lumaMHz', 'lumaPeak']))

// Morph travel curves, tabulated: value at 1025 evenly spaced travel points.
// The glide lerps in travel space; the engine inverts this table by search.
const TRAVEL_N = 1025
const curved = CONTROL_KEYS.filter(k => UI.SLIDER_BY_KEY.get(k)?.curve !== undefined)
L.push(`constexpr int kTravelN = ${TRAVEL_N};`)
L.push(`constexpr int kTravelCount = ${curved.length};`)
L.push(`inline const int kTravelKeys[kTravelCount] = { ${curved.map(k => `C_${k}`).join(', ')} };`)
L.push('inline const float kTravelTable[kTravelCount][kTravelN] = {')
for (const k of curved) {
  const s = UI.SLIDER_BY_KEY.get(k)
  const row = []
  for (let i = 0; i < TRAVEL_N; i++) row.push(fromTravel(s, i / (TRAVEL_N - 1)))
  // sanity: the inverse must agree with the table ends
  void toTravel
  L.push(`  { ${row.map(v => `${num(Math.fround(v))}f`).join(',')} }, // ${k}`)
}
L.push('};')

// ── uniform layout ──
L.push('')
L.push(`constexpr int kNumParams = ${PARAM_DEFS.length};`)
L.push(`constexpr int kParamBytes = ${PARAM_BYTES};`)
L.push(`constexpr int kTileWG = ${TILE_WG};`)
L.push('enum Prm : int {')
PARAM_DEFS.forEach(([n], i) => L.push(`  P_${n} = ${i},`))
L.push('};')
L.push('inline const bool kParamIsU32[kNumParams] = {')
L.push(PARAM_DEFS.map(([n, t]) => `  ${t === 'u32' ? 'true' : 'false'}, // ${n}`).join('\n'))
L.push('};')
L.push('inline const char* const kParamNames[kNumParams] = {')
L.push(PARAM_DEFS.map(([n]) => `  ${cstr(n)},`).join('\n'))
L.push('};')

// ── presets ──
L.push('')
L.push('struct PresetPatch { int key; double value; };')
L.push('struct Preset { const char* name; const char* label; const char* group; bool needsB; int first; int count; };')
const patches = []
const presets = []
for (const p of PRESETS) {
  const first = patches.length
  for (const [k, v] of Object.entries(p.patch)) {
    if (!keyIdx.has(k)) throw new Error(`preset ${p.name}: unknown key ${k}`)
    patches.push(`{ C_${k}, ${num(v)} }`)
  }
  presets.push(`  { ${cstr(p.name)}, ${cstr(p.displayName ?? p.name)}, ${cstr(p.group)}, ${needsSourceB(p) ? 'true' : 'false'}, ${first}, ${patches.length - first} },`)
}
L.push(`constexpr int kNumPresets = ${PRESETS.length};`)
L.push(`inline const PresetPatch kPresetPatches[${patches.length}] = {`)
for (let i = 0; i < patches.length; i += 4) L.push(`  ${patches.slice(i, i + 4).join(', ')},`)
L.push('};')
L.push('inline const Preset kPresets[kNumPresets] = {')
L.push(presets.join('\n'))
L.push('};')

// ── the paperclip's contact points ──
L.push('')
L.push(`constexpr int kNumClipPoints = ${CLIP_POINTS.length};`)
L.push('struct ClipPeak { int key; double value; };')
L.push('struct ClipPointDef { int first; int count; };')
const cp = []
const cpd = []
for (const p of CLIP_POINTS) {
  const first = cp.length
  for (const [k, v] of Object.entries(p.peak)) cp.push(`{ C_${k}, ${num(v)} }`)
  cpd.push(`{ ${first}, ${cp.length - first} }`)
}
L.push(`inline const ClipPeak kClipPeaks[${cp.length}] = { ${cp.join(', ')} };`)
L.push(`inline const ClipPointDef kClipPoints[kNumClipPoints] = { ${cpd.join(', ')} };`)

L.push('')
L.push('} // namespace skillet')
writeFileSync(out, L.join('\n') + '\n')
console.log(`wrote ${out}: ${CONTROL_KEYS.length} controls, ${PARAM_DEFS.length} params, ${PRESETS.length} presets, ${curved.length} travel curves`)
