// Embeds the translated GLSL and each program's binding table into a C++
// header. Run after translate_all.mjs.
import { readFileSync, writeFileSync } from 'node:fs'

const dir = process.argv[2] ?? '../build/glsl'
const out = process.argv[3] ?? '../engine/generated/shaders.gen.h'
const table = JSON.parse(readFileSync(`${dir}/bindings.json`, 'utf8'))

const KIND = { ubo: 'BindKind::Ubo', ssbo: 'BindKind::Ssbo', tex: 'BindKind::Tex', image: 'BindKind::Image', sampler: 'BindKind::Sampler' }
// Raw string literals have a length limit on MSVC (16 KB per piece), so each
// source is split into chunks that the compiler concatenates.
const rawChunks = src => {
  const parts = []
  for (let i = 0; i < src.length; i += 12000) parts.push(`R"GLSL(${src.slice(i, i + 12000)})GLSL"`)
  return parts.join('\n')
}

const L = []
L.push('// GENERATED by tools/gen_shaders.mjs from the videoskillet WGSL (MIT, Colin Diesh). Do not edit.')
L.push('#pragma once')
L.push('namespace skillet {')
L.push('enum class BindKind { Ubo, Ssbo, Tex, Image, Sampler };')
L.push('struct ShaderBinding { int binding; BindKind kind; int unit; const char* name; };')
L.push('struct ShaderProgram { const char* name; const char* stage; const char* src; int wgX, wgY, wgZ; const ShaderBinding* bindings; int numBindings; };')
const names = Object.keys(table).sort()
for (const k of names) {
  const id = k.replace(/\./g, '_')
  const b = table[k].bindings
  L.push(`inline const ShaderBinding kBind_${id}[] = {`)
  for (const x of b) L.push(`  { ${x.binding}, ${KIND[x.kind]}, ${x.unit}, ${JSON.stringify(x.name)} },`)
  if (b.length === 0) L.push('  { -1, BindKind::Ubo, -1, "" },')
  L.push('};')
}
for (const k of names) {
  const id = k.replace(/\./g, '_')
  const src = readFileSync(`${dir}/${k}.glsl`, 'utf8')
  L.push(`inline const char* const kSrc_${id} =\n${rawChunks(src)};`)
}
L.push(`constexpr int kNumPrograms = ${names.length};`)
L.push('inline const ShaderProgram kPrograms[kNumPrograms] = {')
for (const k of names) {
  const id = k.replace(/\./g, '_')
  const t = table[k]
  const ws = t.workgroupSize ?? [0, 0, 0]
  L.push(`  { ${JSON.stringify(k)}, ${JSON.stringify(t.stage)}, kSrc_${id}, ${ws[0] ?? 1}, ${ws[1] ?? 1}, ${ws[2] ?? 1}, kBind_${id}, ${t.bindings.length} },`)
}
L.push('};')
L.push('} // namespace skillet')
writeFileSync(out, L.join('\n') + '\n')
console.log(`wrote ${out}: ${names.length} programs`)
