// Converts the object literal returned by uniformValues() in
// src/core/gpu/uniforms.ts into C++ assignments `p[P_name] = expr;`, so the
// port packs every field with the app's own unit conversions.
import { readFileSync, writeFileSync } from 'node:fs'
const VS = process.env.VS ?? '/home/claude/videoskillet'
const out = process.argv[2] ?? '../engine/generated/uniforms.gen.inc'
const src = readFileSync(`${VS}/src/core/gpu/uniforms.ts`, 'utf8')
const start = src.indexOf('export function uniformValues')
const body = src.slice(src.indexOf('return {', start) + 'return {'.length, src.lastIndexOf('}', src.lastIndexOf('}') - 1))
// split on top-level commas
const items = []
let depth = 0, cur = ''
for (const line of body.split('\n')) {
  const l = line.replace(/\/\/.*$/, '')
  for (const ch of l) {
    if ('([{'.includes(ch)) depth++
    if (')]}'.includes(ch)) depth--
    if (ch === ',' && depth === 0) { items.push(cur.trim()); cur = ''; continue }
    cur += ch
  }
  cur += ' '
}
if (cur.trim()) items.push(cur.trim())
const conv = e => e
  .replace(/\bc\.([A-Za-z0-9_]+)/g, 'c[C_$1]')
  .replace(/Math\.PI/g, 'kPI')
  .replace(/Math\.max\(/g, 'jmax(')
  .replace(/Math\.min\(/g, 'jmin(')
  .replace(/Math\.exp\(/g, 'std::exp(')
  .replace(/Math\.round\(/g, 'jsRound(')
  .replace(/Math\.sqrt\(/g, 'std::sqrt(')
  .replace(/(jmax\([^()]*\)|[A-Za-z_][A-Za-z0-9_.\[\]]*|\([^()]*\))\s*\*\*\s*([0-9.]+)/g, 'std::pow($1, $2)')
const L = ['// GENERATED by tools/gen_uniforms.mjs from videoskillet src/core/gpu/uniforms.ts (MIT, Colin Diesh).']
for (const it of items) {
  const m = it.match(/^([A-Za-z0-9_]+)\s*(?::\s*([\s\S]*))?$/)
  if (!m) throw new Error(`cannot parse: ${it}`)
  const [, name, expr] = m
  const e = expr === undefined ? name : conv(expr.replace(/\s+/g, ' ').trim())
  if (/\bMath\./.test(e) || /\*\*/.test(e)) throw new Error(`unconverted: ${name}: ${e}`)
  L.push(`p[P_${name}] = ${e};`)
}
writeFileSync(out, L.join('\n') + '\n')
console.log(`wrote ${out}: ${items.length} fields`)
